### ISSUE TITLE
Compatibility with material themes

### ISSUE THREAD

**Issue by guger** [maltaisn/recurpickerlib#18]
The library should be compatible with themes of the new MDC library.

Furthermore it looks like the cancel button is not aligned correctly.

It would also be nice if the circular select buttons for the week days would feature a ripple effect.
e.g. with this custom class: https://github.com/guger/Libraries/blob/master/circularimagebutton/src/main/java/at/guger/circularimagebutton/CircularImageButton.kt

**Comment by maltaisn** [comment]
How do you make it compatible? I haven't been doing Android development for several months, I'm just maintaining my libraries, so I'm a little out of the loop. I'm planning a major release in a few weeks with better Kotlin compatibility, better code too, so I'll probably see what I can do then.

**Comment by guger** [comment]
Well, iconpickerdialog and calcdialog are compatible with material themes, but I wasn't able to find out how you managed this...

**Comment by guger** [comment]
The most remarkable problem are the action buttons, which are not textbuttons anymore...

**Comment by guger** [comment]
@maltaisn Is there any way to help you refactoring?

**Comment by maltaisn** [comment]
No, not for now. I'm planning on removing RecurrencePickerView and only use the dialog since the view creates some issues and I don't think anyone really uses it. I will also use a better architecture, probably MVP. I'll do that in a few weeks, maybe you could help with testing afterwards.

I might also just ditch the dialog and go for Google Calendar's style:

DialogFragment for defaults:
![](https://assets.zoom.us/images/en-us/integration/google/mobile/calendar-repeat-options.png)

And fragment for advanced options:
![Screenshot_20190515-125740](https://user-images.githubusercontent.com/33690959/57794270-42c70780-7711-11e9-8522-0a15b15d1b86.png)

**Comment by guger** [comment]
Okay, also looks good! (Perhaps you can also fit this into a dialog?)

FYI: I just noticed why your other libs are "compatible" with material themes... 
I customized the button styles:

```
<style name="IconDialogStyle" parent="IcdStyle">
    <item name="icdDialogButtonStyle">@style/Widget.MaterialComponents.Button.TextButton.Dialog</item>
   </style>
```

Unfortunately, this does not work in this library... Do you set the text color of those buttons manually?

**Comment by dejiapps** [comment]
I'll be willing to help with testing.

**Comment by maltaisn** [comment]
I've been planning to rewrite nearly the whole UI but I don't have much time to work on this right now so don't expect any release soon. Probably in a few months.

**Comment by guger** [comment]
Are there some guidelines you're following? If so, I could try to refactor/rewrite the lib to suggest a new design.. As I'm rewriting the app where I'm using  this lib, it'd really benefit of an updated version of this library!

**Comment by maltaisn** [comment]
I was planning to rewrite everything in Kotlin with MVVM architecture. I'm not familiar with MVVM yet but it should take a few hours to get familiar with. 

The UI must be completely changed. Instead of having a `RecurrenceView` that can be used in either a dialog or an activity, I think there should be two different fragments, one for activities (like the screenshots above) and the other a dialog fragment with a more compact layout.

I'll have the time soon, maybe in a month.

**Comment by maltaisn** [comment]
@guger I'm done rewriting the library if you want to test it. Many things have changed in the API so I suggest you take a look at the demo app. I'll be releasing it in a few days along with the complete documentation. 

I decided against using MVVM after all and went for a simple MVP architecture. Test coverage is almost 100% except for UI. I used material components and themes and it went pretty well although theming did take some time. The new code is in the [v2](https://github.com/maltaisn/recurpickerlib/tree/v2) branch.

Here's a quick preview:
<img src="https://user-images.githubusercontent.com/33690959/67056754-6b698800-f11b-11e9-947a-8cfdd4b550c9.png" width="40%"/>   <img src="https://user-images.githubusercontent.com/33690959/67056755-6b698800-f11b-11e9-9a88-f3534797bf2a.png" width="40%"/>   <img src="https://user-images.githubusercontent.com/33690959/67056756-6b698800-f11b-11e9-9437-d6db5893fb34.png" width="40%"/>   <img src="https://user-images.githubusercontent.com/33690959/67056757-6b698800-f11b-11e9-851a-3c5b3837d031.png" width="40%"/>

**Comment by guger** [comment]
@maltaisn Excellent, looks really good!

**Comment by dejiapps** [comment]
@maltaisn Thanks for your amazing work. I'm going to try it now.
