### ISSUE TITLE
Listeners instead of TargetFragment?

### ISSUE THREAD

**Issue by guger** [maltaisn/recurpickerlib#21]
It's a consistent feature throughout all your libraries, the callback via `setTargetFragment()`.

Why do you prefer this instead of passing a callback?

**Comment by maltaisn** [comment]
To avoid a memory leak. Say you show the dialog from your activity and set the listener. The listener carries a reference to the activity. When the activity is recreated on configuration change, the dialog isn't (since I use `setRetainInstance(true)`), and keeps the old activity reference. This could be avoided by [setting the listener in `onAttachFragment`](https://developer.android.com/training/basics/fragments/communicating), but it's more complicated than using a callback.

However I think you should avoid using `setTargetFragment()` (which is deprecated) and instead show the dialog with `getChildrenFragmentManager()`. According to the documentation, by using `setTargetFragment()`, the caller fragment is retained, which may not be what you want.

At the time, I think I did this because of [this answer](https://stackoverflow.com/a/14808425/5288316) on Stack Overflow and because it's what [Google's documentation](https://developer.android.com/guide/topics/ui/dialogs.html#PassingEvents) recommended.
