### ISSUE TITLE
Recurrence Object and Serialization to/from non-Android

### ISSUE THREAD

**Issue by PeregrineFalcon** [maltaisn/recurpickerlib#34]
Is there a possibility you would ever support extracting the Recurrence object and its Serialization capability out to its own library. I have a tool that is using your (fantastic) recurpickerlib in Android. But would like to be able to generate Recurrence objects that are compatible from a standard Java application.

**Comment by maltaisn** [comment]
Actually the library was not supposed to have its own recurrence class from the start. I realized that early on, and everything that that changed since was to avoid losing too much backwards compatibility. The reason is that there are much better libraries around that support the full RFC 5545 standard (which I didn't know of back then), so there's no point in trying to recreate it. I should've done like SublimePicker (which also provides a recurrence picker) and pass the RRule directly to the picker.

It would certainly be possible to put the Recurrence stuff in a separate non-Android artifact. I thought about it a few times, but never got on with it. The fact is, I don't want to support a separate library. I feel like since it would be separate from the project, people would start asking for better support of the standard, which I feel is pointless, since it already exists. That's not a problem today because the Recurrence is tied with the picker, so support is limited by the UI, not the standard.

In your situation, I would recommend you use one the existing libraries, like [lib-recur](https://github.com/dmfs/lib-recur) (still maintained) or [google-rfc-2445](https://code.google.com/archive/p/google-rfc-2445/) to deal with recurrences. Use recurpickerlib's `Recurrence` class as little as possible, in fact only to interact with the picker. The rest of the time you can move around RRule strings, between your client and server, between your repository and your view model/presenter. And let proguard eat `RecurrenceFinder`.

**Comment by PeregrineFalcon** [comment]
Well that's perfect. Makes complete sense why you don't have it broken out. Appreciate the pointers to lib-recur. I will investigate. My plan is to have the client->server just pass the serialized string around so that should work without issue once the Android side receives it and needs to convert it to recurpickerlibs Recurrence object.

Cheers!
