### ISSUE TITLE
Recurrence(Recurrence.Period.WEEKLY) String Invalid

### ISSUE THREAD

**Issue by PeregrineFalcon** [maltaisn/recurpickerlib#35]
I am using a weekly Recurrence and the default 'presets' for the RecurrencePickerSettings creates the default set. If a user selects 'Every week' the resulting Recurrence returned in onRecurrencePresetSelected() override has a toString() that looks like the following:

`Recurrence{ Every week o }`

If I then attempt to use RRuleFormatter.format() on that Recurrence during the loop on checking 'isRecurringOnDaysOfWeek' none are found. This also occurs in Recurrence class during it's toSting() (which is why the Recurrence to String looks like that).  Then the StringBuilder removes the last two characters. In both cases this is not a valid RFC2445 or RFC5445 string.

If looks like the default Builder for Recurrence sets byDay = 1. Which is causing the problem if nothing else sets the byDay and since the preset doesn't it seems like byDay is becoming one and failing the isRecurringOnDaysOfWeek.

Am I doing something wrong here?

**Comment by maltaisn** [comment]
There's a two bugs here:
- `Recurrence.toString()` should return something like "Recurrence{ Every week on the same day as start date }".
- `RRuleFormatter` should not leave an empty `BYDAY` attribute when formatting such a recurrence. Note that `BYDAY` is not required to make a valid RRule.

Both issues should be fixed in 2.1.4. The problem arises from the fact that default weekly recurrence has a special case. By default it has no days set and instead always occurs on the same day of the week as start date's, so the resulting events in `RecurrenceFinder.find` depends on the start date given. The value of `byDay` in that case is `1` but that doesn't match any day of the week flag.
