### ISSUE TITLE
Day selection UI displays incorrectly in small screens 

### ISSUE THREAD

**Issue by amsanjeev** [maltaisn/recurpickerlib#37]
Currently on small screens or low resolution setting, the day selection buttons rollover and overlap each other  
please check the screenshot to understand better

To replicate the issue , please try the following steps 

1. go to settings > display > display size 
2. change the display size to "largest"
3. open the recurrence selection dialog 

reproduce : yes 
frequency : 5 of 5 (100%)

*attached screenshot is from a P4XL device with the display size set to largest 

![Screenshot (Jan 4, 2021 10_11_37 AM)](https://user-images.githubusercontent.com/818110/103501818-5a6a7b00-4e75-11eb-88cc-2a30d78eb140.png)

**Comment by maltaisn** [comment]
I couldn't reproduce it on a physical Pixel 2 with largest display size set, in the demo app. This is what I get:

![image](https://user-images.githubusercontent.com/33690959/103721267-415bea00-4f9b-11eb-901e-00e783952fd7.png)

This part of the layout uses a `Flow` from the ConstraintLayout library. 

I suggest you try updating the dependency to latest version 2.0.4 if that's not already the case (maybe it's a bug in the library that has been fixed). Other than that perhaps you can try reproducing the issue in a minimal layout and submit an issue at their issue tracker.

There's not much more I can do since I can't reproduce it. Were there any other circumstances that may have caused this? (custom theme, root, other accessibility settings, etc)

**Comment by amsanjeev** [comment]
I tested this further and found that the issue is with the dependency  **_androidx.constraintlayout:constraintlayout_**
The issue is present in both 2.0.3 & 2.0.4 . 
The issue is NOT present in version 2.0.2 or below .

**Comment by maltaisn** [comment]
Did you open an issue at the Google issue tracker?

**Comment by maltaisn** [comment]
This was fixed some time ago in a new constraint layout release.
